# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hwahae' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  use_frameworks!
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.2'
  pod 'SDWebImage', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FSPagerView'

  # Pods for Hwahae

end
